# Generated by Django 4.1.4 on 2022-12-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='date',
            field=models.IntegerField(),
        ),
    ]
